version: '3.8'

services:
  frontend:
    image: marcdroit/quiz-frontend:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == frontend
    depends_on:
      - backend
      - database
    ports:
      - 8080:80
    networks:
      - react-quiz-network

  backend:
    image: marcdroit/quiz-backend:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == backend
    depends_on:
      - database
    environment:
      DB_HOST: quiz-stack_database
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: quiz-db
    expose:
    - 3000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - react-quiz-network

  database:
    image: marcdroit/postgres:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quiz-db
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - react-quiz-network

networks:
  react-quiz-network:
    driver: overlay

volumes:
  postgres-data:
    driver: local